import type { CrewDb, CrewUser, Credential, TalentCard } from './types';

export const CREW_USERS: Record<string, CrewUser> = {
  maker: {
    id: 'u1',
    name: '김서연',
    role: 'maker',
    grade: 'Verified',
    trustScore: 87,
    badges: 12,
    completedProjects: 8,
    deadlineRate: 96,
    avgRating: 4.7,
    skills: ['데이터 분석', 'Figma', '카피라이팅', 'React'],
    region: '대전',
  },
  reviewer: {
    id: 'u2',
    name: '이준혁',
    role: 'reviewer',
    grade: 'Reviewer',
    trustScore: 94,
    badges: 28,
    completedProjects: 22,
    deadlineRate: 100,
    avgRating: 4.9,
    skills: ['코드 리뷰', 'QA', '프론트엔드'],
    region: '대전',
  },
  client: {
    id: 'u4',
    name: '(주)로컬테크',
    role: 'client',
    company: '로컬테크',
    projects: 5,
    activeProjects: 2,
  },
  admin: { id: 'u5', name: '운영자', role: 'admin' },
};

export const FLOW_TASK_ID = 't2';

export const DEMO_NEW_CRED: Credential = {
  id: 'c-demo',
  project: '대전 스타트업 마케팅 데이터 분석',
  role: 'Maker',
  task: '마케팅 데이터 분석·시각화',
  period: '2026.02 - 2026.03',
  skills: ['데이터 분석', 'Figma', '카피라이팅'],
  qaPass: true,
  rating: 4.9,
  trustDelta: '+3',
  issuedAt: '2026-03-24',
  verifyId: 'kim_daejeon_001',
  isNew: true,
};

export const MOCK_TALENTS: TalentCard[] = [
  {
    id: 't1',
    name: '김서연',
    grade: 'Verified',
    trustScore: 87,
    projects: 8,
    deadlineRate: 96,
    rating: 4.7,
    skills: ['React', 'Figma', 'UX'],
    region: '대전',
    available: true,
  },
  {
    id: 't2',
    name: '박민수',
    grade: 'Advanced',
    trustScore: 82,
    projects: 6,
    deadlineRate: 92,
    rating: 4.5,
    skills: ['React', 'TypeScript'],
    region: '세종',
    available: false,
  },
  {
    id: 't3',
    name: '최유나',
    grade: 'Verified',
    trustScore: 79,
    projects: 5,
    deadlineRate: 88,
    rating: 4.6,
    skills: ['CSS', '디자인'],
    region: '대전',
    available: true,
  },
];

export const INITIAL_CREW_DB: CrewDb = {
  projects: [
    {
      id: 'p1',
      name: '대전 스타트업 마케팅 데이터 분석',
      client: '대전 헬스테크',
      status: '진행중',
      progress: 65,
      deadline: '2026-04-15',
      security: '일반',
      budget: '3,200,000원',
      tasks: 8,
      completedTasks: 5,
      modules: ['데이터 수집', '데이터 분석', '시각화'],
      description: '대전 지역 스타트업 마케팅·설문 데이터 분석 (4주) — LER 데모 프로젝트',
    },
    {
      id: 'p2',
      name: '세종시 관광 데이터 정리',
      client: '세종시청',
      status: '진행중',
      progress: 40,
      deadline: '2026-04-30',
      security: '일반',
      budget: '2,000,000원',
      tasks: 6,
      completedTasks: 2,
      modules: ['데이터 수집', '정제', '시각화'],
      description: '관광 데이터 수집/정제/시각화',
    },
    {
      id: 'p3',
      name: '스타트업 IR 자료 디자인',
      client: '넥스트랩',
      status: '검수중',
      progress: 90,
      deadline: '2026-03-25',
      security: '높음',
      budget: '1,800,000원',
      tasks: 4,
      completedTasks: 4,
      modules: ['슬라이드 디자인', '인포그래픽'],
      description: '시리즈A IR 자료',
    },
  ],
  tasks: [
    {
      id: 't1',
      projectId: 'p1',
      name: '메인 히어로 섹션 퍼블리싱',
      status: '승인완료',
      assignee: '김서연',
      difficulty: '중',
      deadline: '2026-03-20',
      skills: ['HTML/CSS', 'React'],
      autoCheck: '통과',
      reviewScore: 4.8,
    },
    {
      id: 't2',
      projectId: 'p1',
      name: '마케팅 데이터 분석·시각화',
      status: '진행중',
      assignee: '김서연',
      difficulty: '중',
      deadline: '2026-03-28',
      skills: ['데이터 분석', 'Figma'],
      autoCheck: null,
      reviewScore: null,
    },
    {
      id: 't4',
      projectId: 'p1',
      name: '반응형 레이아웃 적용',
      status: '제출완료',
      assignee: '최유나',
      difficulty: '중',
      deadline: '2026-03-25',
      skills: ['CSS'],
      autoCheck: '통과',
      reviewScore: null,
    },
  ],
  credentials: [
    {
      id: 'c1',
      project: '로컬푸드 쇼핑몰 리뉴얼',
      role: 'Maker',
      task: '메인 히어로 섹션 퍼블리싱',
      period: '2026.02 - 2026.03',
      skills: ['HTML/CSS', 'React'],
      qaPass: true,
      rating: 4.8,
      trustDelta: '+3',
      issuedAt: '2026-03-20',
      verifyId: 'VRF-2026-0320-A1B2',
    },
    {
      id: 'c2',
      project: '마케팅 리서치 보고서',
      role: 'Maker',
      task: '설문 데이터 분석',
      period: '2026.01 - 2026.02',
      skills: ['Excel', '데이터 분석'],
      qaPass: true,
      rating: 4.6,
      trustDelta: '+2',
      issuedAt: '2026-02-28',
      verifyId: 'VRF-2026-0228-C3D4',
    },
    {
      id: 'c3',
      project: '교육 앱 UX 리서치',
      role: 'Maker',
      task: '사용자 인터뷰 정리',
      period: '2025.11 - 2025.12',
      skills: ['UX 리서치', '인터뷰', '분석'],
      qaPass: true,
      rating: 4.9,
      trustDelta: '+4',
      issuedAt: '2025-12-15',
      verifyId: 'VRF-2025-1215-E5F6',
    },
  ],
};
