import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'sources', 'en');
mkdirSync(outDir, { recursive: true });

const common = [
  ['lang="ko"', 'lang="en"'],
  ['로컬크루', 'LocalCrew'],
  ['대전', 'Regional'],
  ['세종', 'Sejong'],
  ['청주', 'Cheongju'],
];

const experienceRepl = [
  ['<title>로컬크루 체험하기</title>', '<title>LocalCrew — Try the Demo</title>'],
  ['content="지역의 작은 경험을 검증된 커리어로 연결하는 로컬크루 체험하기 페이지"', 'content="LocalCrew demo — connect regional project work to verified career credentials"'],
  ['신뢰도 점수', 'Trust score'],
  ['상위 18%', 'Top 18%'],
  ['마감 준수율 96% · 평균 평점 4.7', '96% on-time · 4.7 avg rating'],
  ['마이크로 크레덴셜', 'Micro-credentials'],
  ['웹 기획 보조', 'Web planning support'],
  ['QA 통과', 'QA passed'],
  ['마감 100% · 평점 4.8 · 3건 수행', '100% on-time · 4.8 rating · 3 projects'],
  ['데이터 정리', 'Data cleanup'],
  ['포트폴리오 자동 생성', 'Auto portfolio'],
  ['지원서형', 'Application'],
  ['프로젝트형', 'Project'],
  ['경력기술서', 'Career summary'],
  ['URL 공유', 'Share URL'],
  ['인재 검색', 'Talent search'],
  ['김서연', 'Sarah Kim'],
  ['박민수', 'Min Park'],
  ['지역의 작은 경험이,<br />', 'Regional project work,<br />'],
  ['<em>검증된 커리어</em>가 되다', '<em>verified credentials</em>'],
  ['로컬크루는 프로젝트 수행 이력, 마이크로 크레덴셜, 포트폴리오 자동 생성을 통해 지역 청년의 실무 경험을 실제 기회와 연결합니다.', 'LocalCrew connects regional talent to real opportunities through project history, micro-credentials, and auto-generated portfolios.'],
  ['체험하기', 'Try demo'],
  ['데모 둘러보기', 'Browse demo'],
  ['로그인 없이 주요 화면을 먼저 확인할 수 있습니다', 'Preview key screens without signing in'],
  ['수행 완료 과업', 'Tasks completed'],
  ['마감 준수율', 'On-time rate'],
  ['발급 크레덴셜', 'Credentials issued'],
  ['대시보드', 'Dashboard'],
  ['프로젝트', 'Projects'],
  ['리뷰 관리', 'Review queue'],
  ['운영', 'Operations'],
  ['관리', 'Admin'],
  ['사용자 관리', 'User admin'],
  ['크레덴셜', 'Credentials'],
  ['{label:"운영",items:', '{label:"Operations",items:'],
  ['{label:"관리",items:', '{label:"Admin",items:'],
];

const mvpRepl = [
  ['<title>로컬크루 | MVP 체험</title>', '<title>LocalCrew | MVP Demo</title>'],
  ['content="로컬크루 역할 기반 MVP 프로토타입"', 'content="LocalCrew role-based MVP prototype"'],
  ['(주)로컬테크', 'LocalTech Inc.'],
  ['운영자', 'Admin User'],
  ['김서연', 'Sarah Kim'],
  ['이준혁', 'Jun Lee'],
  ['박민수', 'Min Park'],
  ['최유나', 'Yuna Choi'],
  ['정하늘', 'Ha-neul Jung'],
  ['한소희', 'So-hee Han'],
  ['UX 리서치', 'UX research'],
  ['코드 리뷰', 'Code review'],
  ['프론트엔드', 'Frontend'],
  ['진행중', 'In progress'],
  ['검수중', 'In review'],
  ['배정중', 'Assigning'],
  ['완료', 'Done'],
  ['배정됨', 'Assigned'],
  ['제출완료', 'Submitted'],
  ['승인완료', 'Approved'],
  ['수정요청', 'Revision'],
  ['반려', 'Rejected'],
  ['일반', 'Standard'],
  ['높음', 'High'],
  ['과업 수행 청년', 'Talent'],
  ['작업물 검수자', 'Project Assessor'],
  ['프로젝트 의뢰 기업', 'Enterprise Client'],
  ['운영 관리자', 'Platform Admin'],
  ['지역의 작은 경험이,<br/><em>검증된 커리어</em>가 되다', 'Regional project work,<br/><em>verified credentials</em>'],
  ['프로젝트 수행 이력, 마이크로 크레덴셜, 포트폴리오 자동 생성을 통해 지역 청년의 실무 경험을 실제 기회와 연결합니다.', 'Connect regional project work to real opportunities through verified history, micro-credentials, and auto portfolios.'],
  ['수행 완료 과업', 'Tasks completed'],
  ['마감 준수율', 'On-time rate'],
  ['발급 크레덴셜', 'Credentials issued'],
  ['체험하기', 'Try demo'],
  ['역할을 선택하고 대시보드에 입장하세요', 'Choose a role to enter the dashboard'],
  ['로 입장', ' dashboard'],
  ['역할을 선택하세요', 'Select a role'],
  ['로그인 없이 주요 화면을 먼저 확인할 수 있습니다', 'Preview key screens without signing in'],
  ['안녕하세요, ', 'Hello, '],
  ['님 ', ''],
  ['오늘의 작업 현황을 확인하세요', 'Review your work status for today'],
  ['신뢰도 점수', 'Trust score'],
  ['상위 18%', 'Top 18%'],
  ['누적 배지', 'Total badges'],
  ['+2 이번 달', '+2 this month'],
  ['마감 준수율', 'On-time rate'],
  ['최근 10건', 'Last 10 tasks'],
  ['평균 평점', 'Avg rating'],
  ['리뷰어 평가', 'Reviewer score'],
  ['진행중 과업', 'Active tasks'],
  ['마감 ', 'Due '],
  ['최근 획득 배지', 'Recent badges'],
  ['보유 기술', 'Skills'],
  ['검증된 수행 이력 배지', 'Verified work badges'],
  ['건', ''],
  ['역할', 'Role'],
  ['수행 기간', 'Period'],
  ['평점', 'Rating'],
  ['신뢰도 변동', 'Trust delta'],
  ['검증 ID:', 'Verify ID:'],
  ['포트폴리오 생성', 'Portfolio builder'],
  ['수행 데이터 기반 자동 포트폴리오', 'Auto portfolio from verified work data'],
  ['템플릿 선택', 'Choose template'],
  ['프로젝트형', 'Project'],
  ['지원서형', 'Application'],
  ['경력기술서형', 'Career summary'],
  ['제안서형', 'Proposal'],
  ['강조 프로젝트', 'Featured projects'],
  ['생성중...', 'Generating...'],
  ['포트폴리오 생성', 'Generate portfolio'],
  ['핵심 역량', 'Core skills'],
  ['수행 실적', 'Track record'],
  ['마감률', 'On-time'],
  ['신뢰도', 'Trust'],
  ['프로젝트 이력', 'Project history'],
  [' 대시보드', ' dashboard'],
  ['프로젝트 진행 현황', 'Project progress overview'],
  ['총 프로젝트', 'Total projects'],
  ['진행중', 'Active'],
  ['검수 대기', 'Pending review'],
  ['1건 확인 필요', '1 needs review'],
  ['누적 집행', 'Total spend'],
  ['원', ' KRW'],
  ['프로젝트 목록', 'Project list'],
  ['새 의뢰', 'New brief'],
  ['프로젝트명', 'Project'],
  ['상태', 'Status'],
  ['진행률', 'Progress'],
  ['마감', 'Due'],
  ['예산', 'Budget'],
  ['인재 검색', 'Talent search'],
  ['검증된 수행 이력 기반 인재 탐색', 'Search talent by verified work history'],
  ['기술 검색 (예: React, Python)', 'Search skills (e.g. React, Python)'],
  ['전체 등급', 'All grades'],
  ['가용', 'Available'],
  ['작업중', 'Busy'],
  ['완료 프로젝트 ', 'Projects completed '],
  ['운영 대시보드', 'Ops dashboard'],
  ['플랫폼 전체 현황 관리', 'Platform-wide overview'],
  ['전체 프로젝트', 'All projects'],
  ['건', ''],
  ['납기 위험', 'At-risk deadlines'],
  ['7일 이내', 'Within 7 days'],
  ['활성 작업자', 'Active contributors'],
  ['대전·세종·청주', 'Regional markets'],
  ['발급 크레덴셜', 'Credentials issued'],
  ['이번 달 +12', '+12 this month'],
  ['프로젝트 현황', 'Project status'],
  ['납기 위험 · 지역 통계', 'At-risk deadlines · regions'],
  ['태스크 ', 'Tasks '],
  ['지역별 참여자', 'Contributors by region'],
  ['명 (', ' people ('],
  ['%)', '%)'],
  ['최근 활동 로그', 'Recent activity'],
  ['님이 ', ' '],
  [' 진행 시작', ' started work'],
  [' 결과물 제출', ' submitted deliverable'],
  [' 검수 완료', ' review completed'],
  ['님 배지 발급:', ' badge issued:'],
  [' 등록', ' registered'],
  ['프로젝트 관리', 'Project admin'],
  ['전체 프로젝트 조회 및 관리', 'View and manage all projects'],
  ['프로젝트 등록', 'Add project'],
  ['← 프로젝트 목록', '← Back to projects'],
  ['총 태스크', 'Total tasks'],
  ['보안', 'Security'],
  ['태스크 목록', 'Task list'],
  ['태스크 추가', 'Add task'],
  ['태스크', 'Task'],
  ['담당', 'Assignee'],
  ['난이도', 'Level'],
  ['자동검증', 'Auto-check'],
  ['상', 'Hard'],
  ['중', 'Medium'],
  ['통과', 'Pass'],
  ['Maker', 'Maker'],
  ['Reviewer', 'Reviewer'],
  ['Client', 'Client'],
  ['Admin/PM', 'Admin/PM'],
  ['로컬푸드 쇼핑몰 리뉴얼', 'Local food mall redesign'],
  ['세종시 관광 데이터 정리', 'Tourism data cleanup'],
  ['스타트업 IR 자료 디자인', 'Startup IR deck design'],
  ['교육 앱 QA 테스트', 'EdTech app QA'],
  ['마케팅 리서치 보고서', 'Marketing research report'],
  ['메인 히어로 섹션 퍼블리싱', 'Hero section publishing'],
  ['상품 카드 컴포넌트 제작', 'Product card component'],
  ['검색 필터 UI 구현', 'Search filter UI'],
  ['반응형 레이아웃 적용', 'Responsive layout'],
  ['관광지 데이터 크롤링', 'Tourism data crawling'],
  ['데이터 정제 및 포맷 변환', 'Data cleanup & formatting'],
  ['설문 데이터 분석', 'Survey data analysis'],
  ['교육 앱 UX 리서치', 'EdTech UX research'],
  ['사용자 인터뷰 정리', 'User interview synthesis'],
  ['랜딩페이지', 'Landing page'],
  ['상품 카드 UI', 'Product card UI'],
  ['검색 필터', 'Search filters'],
  ['데이터 수집', 'Data collection'],
  ['정제', 'Cleaning'],
  ['시각화', 'Visualization'],
  ['슬라이드 디자인', 'Slide design'],
  ['인포그래픽', 'Infographic'],
  ['기능 QA', 'Functional QA'],
  ['UI QA', 'UI QA'],
  ['리포트', 'Report'],
  ['설문 설계', 'Survey design'],
  ['데이터 분석', 'Data analysis'],
  ['보고서', 'Report'],
  ['기존 로컬푸드 쇼핑몰의 프론트엔드를 모던하게 리뉴얼', 'Modern frontend redesign for a local food marketplace'],
  ['세종시 관광 데이터 수집/정제/시각화', 'Tourism data collection, cleanup, and visualization'],
  ['시리즈A IR 자료 디자인', 'Series A investor deck design'],
  ['교육 앱 전면 QA', 'Full QA for an education app'],
  ['지역 소비자 마케팅 리서치', 'Regional consumer marketing research'],
  ['HTML/CSS', 'HTML/CSS'],
  ['미디어쿼리', 'Media queries'],
  ['크롤링', 'Crawling'],
  ['퍼블리싱', 'Publishing'],
  ['반응형', 'Responsive'],
  ['일러스트', 'Illustration'],
  ['로고', 'Logo design'],
  ['인터뷰', 'Interviews'],
  ['분석', 'Analysis'],
  ['리서치', 'Research'],
  ['고급 React 개발', 'Advanced React'],
];

const mvpUiRepl = [
  ['name:"대시보드"', 'name:"Dashboard"'],
  ['name:"내 과업"', 'name:"My tasks"'],
  ['name:"크레덴셜"', 'name:"Credentials"'],
  ['name:"포트폴리오"', 'name:"Portfolio"'],
  ['name:"리뷰 대기"', 'name:"Review queue"'],
  ['name:"프로젝트"', 'name:"Projects"'],
  ['name:"리뷰 관리"', 'name:"Review queue"'],
  ['name:"사용자 관리"', 'name:"User admin"'],
  ['name:"인재 검색"', 'name:"Talent search"'],
  ['{label:"운영",items:', '{label:"Operations",items:'],
  ['{label:"관리",items:', '{label:"Admin",items:'],
  ['company: "로컬테크"', 'company: "LocalTech"'],
  ['세종시청', 'Sejong City Hall'],
  ['Sejong시청', 'Sejong City Hall'],
  ['넥스트랩', 'NextLab'],
  ['에듀플러스', 'EduPlus'],
  ['<h1>마이크로 크레덴셜</h1>', '<h1>Micro-credentials</h1>'],
  ['<h1>내 과업</h1>', '<h1>My tasks</h1>'],
  ['배정된 태스크 관리', 'Manage assigned tasks'],
  ['배정된 Tasks 관리', 'Manage assigned tasks'],
  ['<h1>리뷰 / 평가</h1>', '<h1>Review & rating</h1>'],
  ['구조화된 항목으로 작업 결과 기록', 'Record outcomes with structured criteria'],
  ['<h1>사용자 관리</h1>', '<h1>User admin</h1>'],
  ['<th>프로젝트</th>', '<th>Project</th>'],
  ['<th>프로젝트명</th>', '<th>Project</th>'],
  ['<th>이름</th>', '<th>Name</th>'],
  ['<th>등급</th>', '<th>Grade</th>'],
  ['<th>지역</th>', '<th>Region</th>'],
  ['<th>태스크</th>', '<th>Task</th>'],
  ['<th>담당</th>', '<th>Assignee</th>'],
  ['<th>난이도</th>', '<th>Level</th>'],
  ['<th>상태</th>', '<th>Status</th>'],
  ['<th>자동검증</th>', '<th>Auto-check</th>'],
  ['<th>신뢰도</th>', '<th>Trust</th>'],
  ['<th>마감률</th>', '<th>On-time</th>'],
  ['<th>완료</th>', '<th>Done</th>'],
  ['미통과', 'Not passed'],
  ['QA 통과', 'QA passed'],
  ['마감 준수', 'Deadline adherence'],
  ['요구사항 충족도', 'Requirements met'],
  ['수정 대응 속도', 'Revision turnaround'],
  ['커뮤니케이션 성실도', 'Communication'],
  ['규약 준수도', 'Guideline compliance'],
  ['재작업 불발생', 'No rework needed'],
  ['평가:', 'Review:'],
  ['코멘트', 'Comments'],
  ['작업 결과에 대한 의견', 'Feedback on deliverable quality'],
  ['승인', 'Approve'],
  ['나가기', 'Exit'],
  ['대기', 'Pending'],
  [' 대시보드</h1>', ' dashboard</h1>'],
  ['difficulty: "중"', 'difficulty: "Medium"'],
  ['difficulty: "상"', 'difficulty: "Hard"'],
  ['difficulty==="중"', 'difficulty==="Medium"'],
  ['difficulty==="상"', 'difficulty==="Hard"'],
  ['교육 앱 QA 테스트', 'EdTech app QA'],
  ['스타트업 IR 자료 디자인', 'Startup IR deck design'],
  ['상품 카드 컴포넌트 제작', 'Product card component'],
  ['반응형 레이아웃 적용', 'Responsive layout'],
  ['고급 React 개발', 'Advanced React'],
  ['검증된 수행 이력 배지', 'Verified work badges'],
  ['대시보드', 'Dashboard'],
  ['내 과업', 'My tasks'],
  ['크레덴셜', 'Credentials'],
  ['포트폴리오', 'Portfolio'],
  ['리뷰 대기', 'Review queue'],
  ['리뷰 관리', 'Review queue'],
  ['사용자 관리', 'User admin'],
  ['프로젝트', 'Projects'],
  ['마이크로 크레덴셜', 'Micro-credentials'],
  ['로컬테크', 'LocalTech'],
  ['LER 발급 플로우 체험 (약 2분) →', 'Try LER flow (2 min) →'],
  ['LER 데모에 오신 것을 환영합니다', 'Welcome to the LER demo'],
  ['Maker → Reviewer 순서로 클릭만 하면 LER(검증 배지)이 발급되는 과정을 체험할 수 있습니다. 실제 로그인·결제는 없습니다.', 'Click through Maker → Reviewer to issue a verified LER badge. No login or payment.'],
  ['시작', 'Start'],
  ['1단계 · 결과물 제출', 'Step 1 · Submit deliverable'],
  ["[내 과업]에서 '상품 카드 컴포넌트 제작' 과업의 [결과물 제출] 버튼을 눌러 주세요.", 'Open My tasks and click Submit on Product card component.'],
  ['과업 화면으로', 'Go to tasks'],
  ['2단계 · Reviewer로 전환', 'Step 2 · Switch to Reviewer'],
  ['제출이 완료되면 상단 [역할 전환]에서 Reviewer를 선택한 뒤 [승인하기]를 진행합니다.', 'After submit, use Switch role → Reviewer, then Approve.'],
  ['Reviewer로 전환', 'Switch to Reviewer'],
  ['3단계 · 검수 승인', 'Step 3 · Approve review'],
  ['[리뷰 대기] 화면에서 승인 버튼을 누르면 LER 데이터가 생성됩니다.', 'On Review queue, click Approve to generate LER data.'],
  ['리뷰 화면으로', 'Go to review'],
  ['4단계 · LER 확인', 'Step 4 · View LER'],
  ['[크레덴셜]에서 방금 발급된 검증 ID(VRF-…)를 확인하세요. 이력서가 아닌 증명 데이터입니다.', 'Open Credentials and check the new Verify ID (VRF-…). Proof-of-work, not a resume.'],
  ['크레덴셜 보기', 'View credentials'],
  ['체험 완료', 'Demo complete'],
  ['Enterprise는 [인재 검색]에서 동일한 검증 이력으로 인재를 찾는 흐름을 보여줍니다. 다른 역할도 자유롭게 둘러보세요.', 'Enterprises use Talent search with the same verified history. Explore other roles freely.'],
  ['완료', 'Done'],
  ['건너뛰기', 'Skip'],
  ['데모', 'Demo'],
  ['샘플 데이터', 'Sample data'],
  ['로그인 없음', 'No login'],
  ['LER 발급 플로우 체험', 'LER issuance flow'],
  ['제출', 'Submit'],
  ['검수', 'Review'],
  ['LER 발급', 'LER issued'],
  ['확인', 'Verify'],
  ['역할 전환', 'Switch role'],
  ['① 과업 제출', '① Submit task'],
  ['② 승인하기', '② Approve'],
  ['③ LER 보기', '③ View LER'],
  ['LER 체험 과업', 'LER demo task'],
  ['아래 과업을 제출하면 Reviewer 검수 → LER(검증 배지) 발급까지 이어집니다.', 'Submit below → Reviewer approval → LER badge issued.'],
  ['배정', 'Assigned'],
  ['결과물 제출', 'Submit work'],
  ['제출 완료', 'Submitted'],
  ['Reviewer 승인 대기 중 — 상단에서 Reviewer로 전환하세요.', 'Awaiting Reviewer — switch role at the top.'],
  ['제출됨', 'Submitted'],
  ['배정된 태스크 관리 · LER 데모', 'Assigned tasks · LER demo'],
  ['검수 대기', 'Pending review'],
  ['상품 카드 컴포넌트 제작 — Maker 제출 완료', 'Product card component — submitted by Maker'],
  ['승인 완료', 'Approved'],
  ['LER 발급됨 ·', 'LER issued ·'],
  ['승인 및 LER 발급', 'Approve & issue LER'],
  ['LER 발급 완료', 'LER issued'],
  ['✓ LER 발급 완료 — 학습·고용 기록이 생성되었습니다', '✓ LER issued — learning & employment record created'],
  ['이 데이터는 Enterprise 인재 검색·ATS 연동에 사용됩니다 (데모).', 'Used in Enterprise talent search & ATS integration (demo).'],
  ['LER 방금 발급', 'LER just issued'],
  ['평가: 상품 카드 컴포넌트 제작', 'Review: Product card component'],
];

function apply(html, list) {
  const sorted = [...list, ...common].sort((a, b) => b[0].length - a[0].length);
  for (const [from, to] of sorted) html = html.split(from).join(to);
  return html;
}

writeFileSync(
  path.join(outDir, 'experience.html'),
  apply(readFileSync(path.join(root, 'experience.html'), 'utf8'), experienceRepl),
  'utf8'
);
writeFileSync(
  path.join(outDir, 'localcrew-mvp.html'),
  apply(readFileSync(path.join(root, 'localcrew-mvp.html'), 'utf8'), [...mvpRepl, ...mvpUiRepl, ...experienceRepl])
    .replace('d:"Youth contributor"', 'd:"Talent"')
    .replace('d:"Work reviewer"', 'd:"Project Assessor"')
    .replace('d:"Project client"', 'd:"Enterprise Client"')
    .replace('d:"Platform operator"', 'd:"Platform Admin"')
    .replace('미Pass', 'Not passed')
    .replace('Reviewer · Reviewer', 'Reviewer · Project Assessor'),
  'utf8'
);

console.log('English demo sources written to sources/en/');
